import type { Metadata } from 'next'
import '@/styles/global.css'
import { ThemeProvider } from '@/features/theme/ThemeContext'

export const metadata: Metadata = {
  title: 'Les Productions Majeures',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon-16x16.png',
    apple: '/apple-touch-icon.png',
  },
  manifest: '/site.webmanifest',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
